services:
  mariadb:
    image: mariadb:lts
    # image: itkdev/mariadb:latest
    restart: always
    volumes:
      # https://hub.docker.com/_/mariadb#:~:text=Initializing%20the%20database%20contents
      - .docker/dumps:/docker-entrypoint-initdb.d
    environment:
      # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables/
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_USER=db
      - MARIADB_PASSWORD=db
      - MARIADB_DATABASE=db
    # https://mariadb.com/kb/en/using-healthcheck-sh/
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
